-- appUser
INSERT INTO app_user (adress, age, birthday, city, email, first_name, is_enabled, is_expired, is_locked, last_name, password, role, zip_code) VALUES ('Musterstreet 1', 30, TO_DATE('1990/01/01', 'YYYY/MM/DD'), 'Berlin', 'florin.schikarski@gmail.com', 'Florin', true, false, false, 'Schikarski', '$2a$31$IOVLj67jCNeXEavzp15vqeFiNEYyGN3xPxx7EUCMoxD2O3S/rSqia', 'ADMIN', 10115);
INSERT INTO app_user (adress, age, birthday, city, email, first_name, is_enabled, is_expired, is_locked, last_name, password, role, zip_code) VALUES ('Musterstreet 1', 30, TO_DATE('1990/01/01', 'YYYY/MM/DD'), 'Berlin', 'schikarski98@gmail.com', 'Florin', true, false, false, 'Schikarski', '$2a$31$Z6y/RzaprebbHsBleuHwo.qm7o90ppbil4JTdY7.K5eVtZBrUChB6', 'USER', 10115);


-- cinemaInformation
INSERT INTO cinema_information (adress, city, email, name, phone_number, zip_code) VALUES ('Lange Str. 60', 'Braunschweig', 'astor-braunschweig@gmail.com', 'Astor', 01805012660, 38100);


-- movie
INSERT INTO movie (director, duration, fsk, local_finishing_date, local_release_date, price, synopsis, title, trailer_link) VALUES ('Christopher Nolan', 152, 'FSK_16', TO_DATE('2008/09/20', 'YYYY/MM/DD'), TO_DATE('2008/07/20', 'YYYY/MM/DD'), 10.0, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'The Dark Knight', 'https://www.youtube.com/watch?v=_PZpmTj1Q8Q');
INSERT INTO movie (director, duration, fsk, local_finishing_date, local_release_date, price, synopsis, title, trailer_link) VALUES ('David Fincher', 139, 'FSK_18', TO_DATE('2000/01/11', 'YYYY/MM/DD'), TO_DATE('1999/11/11', 'YYYY/MM/DD'), 10.0, 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'Fight Club', 'https://www.youtube.com/watch?v=qtRKdVHc-cE');
INSERT INTO movie (director, duration, fsk, local_finishing_date, local_release_date, price, synopsis, title, trailer_link) VALUES ('David Fincher', 149, 'FSK_16', TO_DATE('2014/12/03', 'YYYY/MM/DD'), TO_DATE('2014/10/03', 'YYYY/MM/DD'), 10.0, 'With his wife''s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it''s suspected that he may not be innocent.', 'Gone Girl', 'https://www.youtube.com/watch?v=2-_-1nJf8Vg');
    
    -- versions
    INSERT INTO movie_versions VALUES (1, '_2D');
    INSERT INTO movie_versions VALUES (1, 'OV');
    INSERT INTO movie_versions VALUES (2, '_2D');
    INSERT INTO movie_versions VALUES (2, 'OV');
    INSERT INTO movie_versions VALUES (3, '_2D');
    INSERT INTO movie_versions VALUES (3, 'OV');


    -- cast
    INSERT INTO movie_cast VALUES (1, 'Heath Ledger');
    INSERT INTO movie_cast VALUES (1, 'Christian Bale');
    INSERT INTO movie_cast VALUES (1, 'Gary Oldman');
    INSERT INTO movie_cast VALUES (2, 'Edward Norton');    
    INSERT INTO movie_cast VALUES (2, 'Brad Pitt');
    INSERT INTO movie_cast VALUES (2, 'Helena Bonham Carter');
    INSERT INTO movie_cast VALUES (3, 'Ben Affleck');
    INSERT INTO movie_cast VALUES (3, 'Rosamund Pike');
    INSERT INTO movie_cast VALUES (3, 'Neil Patrick Harris');
    
    -- genres
    INSERT INTO movie_genres VALUES (1, 'ACTION');
    INSERT INTO movie_genres VALUES (1, 'DRAMA');
    INSERT INTO movie_genres VALUES (1, 'THRILLER');
    INSERT INTO movie_genres VALUES (2, 'DRAMA');
    INSERT INTO movie_genres VALUES (3, 'DRAMA');
    INSERT INTO movie_genres VALUES (3, 'THRILLER');


-- theatre
INSERT INTO theatre (has_love_seats, number, rows_total, seats_per_row, seats_total, threed) VALUES (true, 1, 15, 20, 300, true);

    -- rows
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'A', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'B', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'C', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'D', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'E', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'F', 'BOX', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'G', 'BOX', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'H', 'BOX', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'I', 'BOX', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'J', 'BOX', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'K', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'L', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'M', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (false, 'N', 'PARQUET', 20, 1);
    INSERT INTO theatre_rows (front_row, row_letter, row_rank, seats_per_row, theatre_id) VALUES (true, 'O', 'PARQUET', 20, 1);
    
    -- seats
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 1, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 2, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 3, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 4, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 5, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 6, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 7, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 8, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 9, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 10, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 11, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 12, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 13, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 14, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 15, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 16, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 17, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 18, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 19, 'NORMAL', false, 1);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('A', 20, 'NORMAL', false, 1);
    
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 1, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 2, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 3, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 4, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 5, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 6, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 7, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 8, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 9, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 10, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 11, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 12, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 13, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 14, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 15, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 16, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 17, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 18, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 19, 'NORMAL', false, 2);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('B', 20, 'NORMAL', false, 2);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 1, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 2, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 3, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 4, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 5, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 6, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 7, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 8, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 9, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 10, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 11, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 12, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 13, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 14, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 15, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 16, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 17, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 18, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 19, 'NORMAL', false, 3);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('C', 20, 'NORMAL', false, 3);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 1, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 2, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 3, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 4, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 5, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 6, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 7, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 8, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 9, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 10, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 11, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 12, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 13, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 14, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 15, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 16, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 17, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 18, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 19, 'NORMAL', false, 4);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('D', 20, 'NORMAL', false, 4);
    
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 1, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 2, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 3, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 4, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 5, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 6, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 7, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 8, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 9, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 10, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 11, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 12, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 13, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 14, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 15, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 16, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 17, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 18, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 19, 'NORMAL', false, 5);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('E', 20, 'NORMAL', false, 5);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 1, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 2, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 3, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 4, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 5, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 6, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 7, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 8, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 9, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 10, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 11, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 12, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 13, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 14, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 15, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 16, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 17, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 18, 'FOOTREST', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 19, 'LOVE_SEAT', false, 6);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('F', 20, 'LOVE_SEAT', false, 6);
    
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 1, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 2, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 3, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 4, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 5, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 6, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 7, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 8, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 9, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 10, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 11, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 12, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 13, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 14, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 15, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 16, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 17, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 18, 'FOOTREST', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 19, 'LOVE_SEAT', false, 7);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('G', 20, 'LOVE_SEAT', false, 7);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 1, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 2, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 3, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 4, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 5, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 6, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 7, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 8, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 9, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 10, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 11, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 12, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 13, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 14, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 15, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 16, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 17, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 18, 'FOOTREST', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 19, 'LOVE_SEAT', false, 8);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('H', 20, 'LOVE_SEAT', false, 8);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 1, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 2, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 3, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 4, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 5, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 6, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 7, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 8, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 9, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 10, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 11, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 12, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 13, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 14, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 15, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 16, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 17, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 18, 'FOOTREST', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 19, 'LOVE_SEAT', false, 9);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('I', 20, 'LOVE_SEAT', false, 9);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 1, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 2, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 3, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 4, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 5, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 6, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 7, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 8, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 9, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 10, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 11, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 12, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 13, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 14, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 15, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 16, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 17, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 18, 'FOOTREST', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 19, 'LOVE_SEAT', false, 10);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('J', 20, 'LOVE_SEAT', false, 10);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 1, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 2, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 3, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 4, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 5, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 6, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 7, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 8, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 9, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 10, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 11, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 12, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 13, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 14, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 15, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 16, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 17, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 18, 'FOOTREST', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 19, 'LOVE_SEAT', false, 11);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('K', 20, 'LOVE_SEAT', false, 11);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 1, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 2, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 3, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 4, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 5, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 6, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 7, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 8, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 9, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 10, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 11, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 12, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 13, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 14, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 15, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 16, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 17, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 18, 'FOOTREST', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 19, 'LOVE_SEAT', false, 12);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('L', 20, 'LOVE_SEAT', false, 12);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 1, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 2, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 3, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 4, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 5, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 6, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 7, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 8, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 9, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 10, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 11, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 12, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 13, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 14, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 15, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 16, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 17, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 18, 'FOOTREST', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 19, 'LOVE_SEAT', false, 13);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('M', 20, 'LOVE_SEAT', false, 13);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 1, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 2, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 3, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 4, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 5, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 6, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 7, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 8, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 9, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 10, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 11, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 12, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 13, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 14, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 15, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 16, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 17, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 18, 'FOOTREST', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 19, 'LOVE_SEAT', false, 14);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('N', 20, 'LOVE_SEAT', false, 14);

    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 1, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 2, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 3, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 4, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 5, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 6, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 7, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 8, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 9, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 10, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 11, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 12, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 13, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 14, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 15, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 16, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 17, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 18, 'FOOTREST', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 19, 'LOVE_SEAT', false, 15);
    INSERT INTO theatre_seats (row_letter, seat_number, seat_type, taken, row_id) VALUES ('O', 20, 'LOVE_SEAT', false, 15);